baseURL = "https://jonjaques.github.io/jonjaques.com/"
theme = "site"
enableemoji = true
title = "Jon Jaques Personal Site"
minify = true

[params]
  AuthorName = "Jon Jaques"
  AuthorEmail = "me@jonjaques.com"
  AuthorEmailHash = "4ba52f2fda7001cae96fcbbdf7a84331"
  AuthorTwitter = "jaquers"
  AuthorGithub = "jonjaques"
  AuthorGitlab = "jonjaques"
